#!/bin/bash
#A linha acima serve para identificar o interpretador de comandos, isso porque alguns shells não reconhecem alguns comandos.
apt-get update
#update é usado para re-sincronizar os ficheiros de índices de pacotes a partir das suas fontes. Os índices dos pacotes
#disponíveis são obtidos a partir das localizações em /etc/apt/sources.list. Por exemplo, quando se usa um arquivo Debian, este
#comando recolhe e analisa os ficheiros Packages.gz para que a informação sobre pacotes novos e actualizados fique disponível. Um
#update deve ser sempre executado antes de um upgrade ou dist-upgrade. Por favor note que a medição do processo total ira estar
#incorrecta pois o tamanho dos ficheiros de pacotes não pode ser conhecido com antecedência.

apt-get upgrade -y
#upgrade é usado para instalar as versões mais recentes de todos os pacotes presentemente instalados no sistema a partir das
#fontes enumeradas em /etc/apt/sources.list. Os pacotes presentemente instalados com versões novas são obtidos e instalados; em
#nenhumas circunstâncias os pacotes presentemente instalados serão removidos, nem pacotes já instalados serão obtidos e
#instalados.Os pacotes presentemente instalados com novas versões e que não possam ser actualizados sem alterarem o estado da
#instalação de outro pacote serão deixados na versão presente. Deve ser executado primeiro um update para que o apt-get fique a
#saber que estão disponíveis novas versões de pacotes.

apt install ubuntu-restricted-extras -y
apt-get install language-pack-gnome-pt language-pack-pt-base -y
apt-get install gimp -y
apt install brasero -y
apt install firefox -y
apt install vim -y
apt-get install thunderbird -y
apt-get install evince -y
apt-get install x11vnc -y
apt install libreoffice -y
apt install pinta -y
apt-get install inkscape -y
apt-get install chromium-browser -y
apt install vlc -y
wget https://go.skype.com/skypeforlinux-64-alpha.deb -O skype.deb
sudo dpkg -i skype.deb
sudo apt install -f

